### PR TITLE
Add function exercise to episode 01

### PR DESCRIPTION
**Pull request by aschoenr**
Added function exercise to episode 00. This exercise asks the student to write a function that takes two lists as parameters as return a dictionary with the first list as the keys and the second list as the values. This will force the student to use many of the ideas presented in a relatively short function. This submission was done as a part of the instructor training checkout steps.

### CODE REVIEW

**Comment by wrightaprilm** [comment]
This looks good to me. I am a little worried about the length of this lesson, though. When you taught it, how did it go, @qjcg? Should we pull something out to merge this in? Since this is a combined function-dictionary question, I would be OK replacing our current dictionary question with this one. 

I've opened issue #81 to discuss if the lessons are overfull or not. I'm going to hold off on merging this unless anyone else feels strongly.

**Comment by willingc** [comment]
@wrightaprilm I actually like this suggested Challenge by @aschoenr as an optional take-home or advanced challenge.

**Comment by wrightaprilm** [comment]
Since no one else has weighed in on lesson 1 being overfull, I'm going to add this in to the lesson. I would normally handle this by dictionary = dict(zip(keys, values)). But perhaps for this audience, I should break this out into a loop in the instructors guide? Or point them to use the ? for help with the dict and zip functions? Thoughts?

**Comment by tracykteal** [comment]
Thanks all. Please hold off on merging until after the lesson release this week.

**Pull request closed without merging**
