### PR TITLE
Refactoring of the introductory material, data download, and library intro

### PR DESCRIPTION
**Pull request by justbennet**
There were several issues all confounded together at the beginning of the lesson.

Downloading data
Putting the lesson overview several sections into the lesson
Mixing descriptions of the data with explaining libraries

I did not see a good way to disentangle them, so I took the hopefully forgivable
liberty of doing a substantial reorganization and rewrite of the several sections.

There are so many changes, that comparing them in rendered form side-by-side
will probably be more productive than looking at the diff, which isn't so
informative because material moved around.

I tried to preserve all the points covered in the original but to make the path through
them a bit smoother.  I'm sure there is room for improvement.

### CODE REVIEW

**Comment by qjcg** [comment]
Thanks for this @justbennet---keeping up the good work I see! Rewriting and refactoring with clarity in mind is always valuable and important.

I'm not able to review this in detail right away, but will certainly have a chance to look over it it before my workshop in May. (Of course, others reading this are welcome to offer feedback too).

**Comment by wrightaprilm** [comment]
I'm unlikely to be able to look in-depth until the second week in May. When is your workshop, @qjcg? Maybe we can set final merging to happen after the material has been tested in real time?

**Comment by qjcg** [comment]
Hi @wrightaprilm! My workshop is on May 4-5. I'll certainly be reviewing and revising in the lead up to that, and happy to share teaching feedback as well.

**Comment by justbennet** [comment]
@qjcg I should be able to incorporate any changes you'd like in the run-up to your workshop.

**Comment by tracykteal** [comment]
Thanks all! I'm giving this an 'after lesson release' label, since it's a relatively significant update. Could be great for the next release.

**Pull request closed without merging**
