### PR TITLE
03-index-slice-subset.md: improve wording

### PR DESCRIPTION
**Pull request by welozano**
The  sentence refers to x > 5, I think there is an extra "not"

Wil

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Thanks, @welozano! good catch! We can merge this as is. However, I'd like to suggest that we spend a bit more time and rewrite this paragraph a bit as it's not super well written.

My suggestion (feel free to improve):

> When we ask Python whether `x` is greater than `5`, it returns `False`. This is Python's way to say "No". Indeed, the value of `x` is `5`, and `5` is not greater than `5`.

@wrightaprilm, please chime in. :)

**Comment by wrightaprilm** [comment]
I like your replacement text, Maxim. If you're willing to add it in, @welozano, we would very much appreciate it!

**Comment by welozano** [comment]
Hi, the suggestion looks pretty good. I just added as @maxim-belkin suggested.
Wil

**Comment by wrightaprilm** [comment]
Great, thanks @welozano!

**Pull request merged**
