### PR TITLE
Link to new conda homepage

### PR DESCRIPTION
**Pull request by katrinleinweber**
See diff ;-)

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Thanks, Katrin. When I go to https://conda.io it redirects me to https://conda.io/en/latest
Should we use this shorter url?

**Comment by katrinleinweber** [comment]
Exactly to shave off the redirect time, was why I'd suggest the exact URL ;-)
If they ever change it, they seem likely to redirect it as well.

**Comment by maxim-belkin** [comment]
Hmmm, I was not concerned with redirection time but with pointing to "/en/" site, _but_... I have to agree with you here for several reasons: 

1. in my tests (I used http://www.serp-perception.com) redirects were taking 50% of page loading time
2. redirection was taking close to a second (~ 0.7 - 0.8 seconds), which is... not nice
3. The website uses 302 redirect, which is a temporary redirect. It means they might change it in the future or even remove it completely.

Thanks, Katrin!

**Comment by katrinleinweber** [comment]
You're welcome & thanks measuring! Good to know that female intuition was confirmed here ;-D

**Pull request merged**
