### PR TITLE
added time estimates

### PR DESCRIPTION
**Pull request by tracykteal**
Added initial timing estimates and the number of challenges for the episodes

A first pass at https://github.com/datacarpentry/python-ecology-lesson/issues/138

### CODE REVIEW

**Comment by qjcg** [comment]
Thanks @tracykteal for going through and doing these initial estimates!

Overall LGTM, but I suspect the timing for the exercises is underestimated.

I suggest we allocate exercise timings in units of either 5 or 10 minutes to account for instructor explanations, the inevitable learner questions and issues that arise. Allocations of 2-3 minutes for an exercise in my experience would rarely be realistic.

@wrightaprilm (and anyone else reading), what are your thoughts?

**Comment by tracykteal** [comment]
Ha! I was doing it as number of exercises, rather than amount of time. Were you wondering why I thought things were taking 6 minutes? :) I'll go update that splitting the time with teaching and challenges.

**Comment by tracykteal** [comment]
I updated the PR. In general it seems there's slightly more than 50% of any lesson for challenge time, so I estimated things that way.

**Comment by qjcg** [comment]
Haha... well knowing now that before you were listing the number of exercises and not the timing in minutes, that makes *way* more sense.

The updated timings look great!

I don't know if there's an "official" way we can ask instructors to comment / suggest updates to our timing estimates during or after a workshop (ex: in an email from us?), but I think it would be a good idea for keeping these timings realistic going forward.

Merging these initial estimages for now. Thanks!

**Comment by tracykteal** [comment]
Asking for time estimate corrections could be something we do in discussion sessions. I'll suggest that as an idea to the mentoring group.

**Pull request merged**
