### PR TITLE
added information about indexes in a dataframe

### PR DESCRIPTION
**Pull request by snamburi3**
The DataFrame index was not explained in the lesson. I have added some information about that.

### CODE REVIEW

**Comment by wrightaprilm** [comment]
Looking good, thanks for your contribution! Would you mind adding a little bit to the sentence where you say that the index is not actually a column in the dataframe explaining what the index _is_? I think _is not_ statements work best when paired with an _is_. 

Thanks!

**Comment by snamburi3** [comment]
You are right! In the new commit, I explained about what an index is.  what do you think of the new sentence?

**Comment by wrightaprilm** [comment]
I like that a lot! Look good to you, @qjcg?

Thanks for contributing! Is this for instructor training?

**Comment by qjcg** [comment]
Looks good to me! Thanks for the ping @wrightaprilm, and thanks for contributing @snamburi3!

**Pull request merged**
