### PR TITLE
Remove dep

### PR DESCRIPTION
**Pull request by wrightaprilm**
Removing the deprecated lesson file, per the release checklist. The deprecated lesson on plotting can still be accessed in _extras, if it is useful to an instructor.

### CODE REVIEW

**Comment by wrightaprilm** [comment]
I've accidentally included the fix to the putting it all together lesson code block. I'm not sure how to separate these, @maxim-belkin

**Comment by maxim-belkin** [comment]
just a sec...

**Comment by maxim-belkin** [comment]
April, please have a look.

**Comment by wrightaprilm** [comment]
Oh, perfect. Thanks!

**Pull request merged**
