### PR TITLE
Small fixes (typos)

### PR DESCRIPTION
**Pull request by BinxiePeterson**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Thank you, Bianca. All changes look good to me. My only suggestion would be
to keep ”Because” but I’ll let you and April make a decision on that.

**Comment by wrightaprilm** [comment]
I could go either way. Since we're right before the release deadline, I'll merge as is to get it off our plates. Thanks, Bianca!

**Comment by BinxiePeterson** [comment]
As I go through the rest of the lesson, I'll fix if needed, and I'll change "Since" back to "Because". When is the release?

**Comment by maxim-belkin** [comment]
> When is the release?

Last Tuesday. But April used her magic wand to delay it.

**Pull request merged**
