### PR TITLE
added a maintainer

### PR DESCRIPTION
**Pull request by raynamharris**
Maxim Belkin is listed as a maintainer on the DC lessons page

### CODE REVIEW

**Comment by raynamharris** [comment]
might also want to update the README as well

**Comment by wrightaprilm** [comment]
Thanks! Recent ch-ch-changes.

**Comment by maxim-belkin** [comment]
I was an undercover maintainer! 👮

**Comment by wrightaprilm** [comment]
But now you're the Pull Request Panda 🐼, instantly spotting whatever dumb thing I've caused by forgetting to branch.

**Pull request merged**
