### PR TITLE
Changes to use downloaded files instead of URL for data

### PR DESCRIPTION
**Pull request by justbennet**
Changed to
    pd.read_csv("surveys.csv")
since the text prior to the reads talks about downloading the file and
loading the file.

I made a couple of miscellaneous minor changes as follows:

Removed
    * Learn about data slicing and indexing.
from the Learning Objectives because it doesn't seem to be covered here.

Regularized to `.csv` throughout.

In Overview, changed plot (the variable) to plot_id, to avoid confusion.

Added a bit of text about the use of the pd alias for pandas on the internet, as it seemed worth mentioning there.

### CODE REVIEW

**Comment by justbennet** [comment]
This is for SWC/DC instructor training/certification, if this is an appropriate pull request for that.

**Comment by justbennet** [comment]
My apologies.  I made two changes and pushed them my clone before I realized they would all show up as pull requests.  I tried to revert this in my clone to retract them, but that seems not to have worked as I might have thought.  Please decline d3f5ac2.  The other is benign, as it is just reflowing a paragraph.  I am creating a new branch to do further work, as I should have done at first.

Now I have a 'war story' for the git class.  ;-(   Sorry for the extra work.

**Comment by qjcg** [comment]
Hi @justbennet! Thanks for your contributions. My comments follow:

#### commit 20870a0

The URL -> local CSV changes are good. However, I wouldn't completely remove the slicing and indexing learning objective, since we do in fact deal with [indexing](http://pandas.pydata.org/pandas-docs/stable/indexing.html#basics) in the "starting with data" lesson whenever we select a single column from a DataFrame (ex: [`surveys_df['weight'].describe()`](https://github.com/datacarpentry/python-ecology-lesson/blob/5b9e2daa61c2fd215011707009565b400de8a91b/01-starting-with-data.md#groups-in-pandas)), though upon quick review, it seems you're right that we don't deal with [slicing](http://pandas.pydata.org/pandas-docs/stable/indexing.html#slicing-ranges) in that lesson (we get to it in lesson 2). An improved objective that would better reflect the lesson content might be something like: "Learn about indexing DataFrames by column".

#### commit fc9411b

Looks good to me!

#### Commits unrelated to this PR in your gh-pages branch
As you mentioned, you pushed some further unrelated commits to your gh-pages branch after submitting this PR. In general, [we recommend](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/CONTRIBUTING.md#working-with-github) making changes and submitting short, focused PRs from separate topic branches. I've included detailed instructions on how you could revise your work (taking into account the suggestions I've made here) and submit a new PR from a new topic branch below.

#### How to revise your work and submit a new PR

```shell
# should contain the changes you submitted in this PR
cd your-fork-repo

# add a read-only remote for the datacarpentry/python-ecology-lesson repo, naming it "upstream",
# and get the latest upstream commits (will not affect your local work)
git remote add upstream https://github.com/datacarpentry/python-ecology-data
git fetch upstream

# create a new branch named to describe your changes (a "topic branch"),
# with a commit history identical to upstream's gh-pages branch
git checkout -b cleanup-lesson-1 upstream/gh-pages

# check out the version of your file from the origin/gh-pages branch and add it to the **staging area**
# (this is just how git-checkout works, it won't check out  a file directly to your working tree)
# NOTE: this assumes the remote corresponding to your fork is named "origin", which it likely is
git checkout origin/gh-pages -- 01-starting-with-data.md

# move the changes to 01-starting-with-data.md out of the staging area and
# into the working tree for now, as you want to revise before staging & comitting
git reset HEAD 01-starting-with-data.md

# REVISE REVISE REVISE
nano 01-starting-with-data.md

# when ready, stage and commit as usual
git add 01-starting-with-data.md
git commit

# push your topic branch to your fork on GitHub ("origin")
git push origin cleanup-lesson-1

# Now you can submit a new pull request based on your topic branch via GitHub!
```

If the above steps involve too many git acrobatics, please let me know and I'll happily integrate the discussed changes myself. My thinking here is that this could be a good learning opportunity. If you do follow the above steps yourself and submit a new PR, I'll close this PR once I've received your new one.

**Comment by justbennet** [comment]
John,

I will certainly try to follow the instructions for recovery.  If that fails, I'll transfer the PR changes to an isolated commit from the carpenterbennet account and let you know.  It may take me a day or two, as I am back at my day job.

Yes, I took the slicing out because it's in its own lesson now.  I have some other changes related to the content, but, as you say, I was waiting to make them so I could isolate them eac into topical PRs that could be considered separately.

If "How to refer to columns (variables) within a Pandas data frame" sound as a learning objective?  If that seems good, I'll put in a  PR for it.  Separately.  :-)  If there's more discussion needed, it can take place on that instead of here.

Thanks for your continuing patience.

**Comment by qjcg** [comment]
Re: taking a few days to resubmit: no problem!

> If "How to refer to columns (variables) within a Pandas data frame" sound as a learning objective? If that seems good, I'll put in a PR for it. Separately. :-) If there's more discussion needed, it can take place on that instead of here.

It's a good start. We can fine tune the language if needed in the discussion on a the new PR you'll submit.

> Thanks for your continuing patience.

Thank you for your contributions!

**Comment by justbennet** [comment]
@qjcg I created a new pull request, #52, that contains just the changes intended.  If you can decline and close this one and accept or request revisions  to that one, I think we're finally on track.

**Comment by qjcg** [comment]
Great, thanks @justbennet ! Closing this issue, will deal with your proposed changes in #52.

**Pull request closed without merging**
