### PR TITLE
Link redirect on line 23?

### PR DESCRIPTION
**Pull request by doujouDC**
Hi, on line 23, I get the follow error when I click on the "follow the directions" link: Oops! Nothing here...

Please delete this line and the text below before submitting your contribution.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.  

---

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Thank you for the report, Doug. It should be bringing you to https://datacarpentry.org/python-ecology-lesson/setup.html (but it does not). I think I know the reason why (the problem is spefici to data-carpentry lessons).

Before we fix it globally, could you please change `[lesson-setup]` to `({{page.root}}{% link setup.md %})` in this PR? (Also, please wrap the lines to not exceed 100-character limit.) :)

**Comment by maxim-belkin** [comment]
@fmichonneau, to make links that use `{{relative_root_path}}` work, we need to add `{% include base_path.html %} ` to every file that uses them. Is there a way to make every episode auto-include this one?

**Comment by maxim-belkin** [comment]
Actually, looks like all we have to do is add `{% include base_path.html %}` to `links.md` file...

**Comment by maxim-belkin** [comment]
I created a PR upstream (carpentries/styles#405) that should resolve this issue.

**Comment by doujouDC** [comment]
Hey, this was my first pull-request (yikes) so I want to make sure I do not need to do anything else. #newbie

**Comment by maxim-belkin** [comment]
I apologize for rush-fixing this issue myself. I usually don't do that but there are two reasons I did it this time:
1. This bug is kind of a "show-stopper" in my view so I wanted to fix it ASAP. The origin of the problem is in the [styles](https://github.com/carpentries/styles) repository (that we merge into this one from time to time).
2. This PR is basically a report of the problem -- we use [Issues](https://github.com/datacarpentry/python-ecology-lesson/issues) for that. I would be happy to help you with your next PR, if you're OK with that. Otherwise, just tag April (@wrightaprilm) and she'll chime in when she can.

**Comment by doujouDC** [comment]
Hey,

Not worries...I am not sure I would even know how to fix this on my own.

Cheers

Doug

**Pull request closed without merging**
