### PR TITLE
Modified 01starting-with-data.md to use .csv files instead of URLs

### PR DESCRIPTION
**Pull request by justbennet**
This is the cleaned up version of my instructor training pull request.  John slipped in a change to the
Python doc, which I incorporated, hence it appears there are two commits to this pull request instead of one.  This should result in all and only the changes I intended to make.  Sorry for the bumbling.

This addresses a concern expressed by @mboisson in Issue 24.

### CODE REVIEW

**Comment by qjcg** [comment]
Hi @justbennet : I notice that you still remove the "slicing and indexing" learning objective without replacing it with something more accurate. In fact, I think  updating that learning objective should probably be a separate PR.

**Comment by justbennet** [comment]
OK.  I can restore it.  Is everything else good?

**Comment by qjcg** [comment]
Yes, the rest looks good to me.

**Comment by justbennet** [comment]
Should be good now.

**Comment by qjcg** [comment]
Great, merged, thank you!

CC: @gvwilson

**Comment by qjcg** [comment]
Also, quick note: though this PR is related to #24, it doesn't fully resolve it. I'll be teaching in early May and plan to look more closely at that issue before then.

**Comment by justbennet** [comment]
@qjcg Yes.  I am hoping to get you another pull request with some suggested changes to the beginning of the lesson that should address the rest of the issue and, I hope, make the presentation a bit smoother.

**Comment by qjcg** [comment]
Sounds good!

**Comment by justbennet** [comment]
@qjcg, I submitted PR #54 just now, which is a revision of the first several sections.  I hope there is something there you can use.  I'll switch to that channel for further discussion. I hope I didn't overstep.

**Pull request merged**
