### PR TITLE
Update from https://github.com/swcarpentry/styles

### PR DESCRIPTION
**Pull request by ctb**
Work in progress!

Update repo styles from central swcarpentry styles.

See https://github.com/datacarpentry/python-ecology-lesson/issues/92#issuecomment-269800966

### CODE REVIEW

**Comment by ctb** [comment]
(Please feel free to swipe this merge if you want to take over the PR!)

**Comment by ctb** [comment]
A few obvious issues --

* there's a ':' before the page title.
* no datacarpentry logo

**Comment by mkuzak** [comment]
@ctb I merged the conflicts in this pull request and created a new pull request #130
_config.yml still needs to be updated to fix mentioned ':' in the page title

**Comment by ctb** [comment]
Closed in favor of #130!

**Pull request closed without merging**
