### PR TITLE
Update 01-short-introduction-to-Python.md

### PR DESCRIPTION
**Pull request by abenaa07**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Thank you for the PR, @abenaa07!

I think it would be better to submit this request against `setup.md` file, where we discuss how to prepare for the workshop.

**Comment by maxim-belkin** [comment]
What do you think, @wrightaprilm?

**Comment by wrightaprilm** [comment]
I agree. Under the "Software" header in Setup.md, we mention that we focus on Python 3, but not what that means. This would go well there.

**Comment by maxim-belkin** [comment]
a gentle ping, @abenaa07!

**Comment by tobyhodges** [comment]
I'm helping the current lesson Maintainers process outstanding pull requests on this repository, in preparation for [transition to the new lesson infrastructure](https://carpentries.github.io/workbench/faq.html#update-fork-from-styles).

The setup instructions for this lesson have undergone pretty extensive changes since this pull request was opened, so I am going to close it. @abenaa07 thank you very much for contributing. If you still think this change would improve the lesson, please open a new pull request.

**Pull request closed without merging**
