### PR TITLE
Align "Pandas and matplotlib" answer code with challenge text

### PR DESCRIPTION
**Pull request by katrinleinweber**
I'm very confused about that section in 08-putting-it-all-together. These are some simple improvement suggestions (particularly based on the [text "September 11 through 15"](https://github.com/datacarpentry/python-ecology-lesson/blame/3adda6a28161bb6ddacb30f819e8a0c95acc2498/_episodes/08-putting-it-all-together.md#L269)).

Additionally, we could clarify in this PR:

- [ ] Why #320 & #399 both duplicated the initial code block? ~~cc @ wrightaprilm~~
- [ ] How the "Alarm level" that's mentioned in #320 and [shown in the figure](https://github.com/datacarpentry/python-ecology-lesson/blob/3adda6a28161bb6ddacb30f819e8a0c95acc2498/fig/08_flood_event.png) can be added to the code?

### CODE REVIEW

**Comment by wrightaprilm** [comment]
Hi Katrin,

Due to the nature of my separation from this organization (not protected by the CoCC from a serial sex harasser), I don't feel comfortable or safe answering questions in this space. Sorry I can't be more helpful.

Unsubscribed.

**Comment by katrinleinweber** [comment]
My apologies! I didn't know that :-/ Understood.

**Comment by fmichonneau** [comment]
@katrinleinweber as of October 2019, April Wright does not wish to be contacted with any query regarding their contributions to this repository. Please direct all your queries to the maintainer (@maxim-belkin).

**Review by maxim-belkin — APPROVED** [review]

**Comment by maxim-belkin** [comment]
Thanks for fixing the challenge, @katrinleinweber!

**Pull request merged**
