### PR TITLE
check_env script + instructions in pythonSetup.html

### PR DESCRIPTION
**Pull request by hugobowne**
Dealing with #83 : I have 

- added a check_env.py in dir _includes/scripts
- edited pythonSetup.html to give instructions on running it.

### CODE REVIEW

**Comment by wrightaprilm** [comment]
Sorry I'm so late getting back to this. This looks good to me, so I'm going to merge this and give it a quick test, and have my undergrad also test it. So I'll leave the issue open. Thanks so much for doing this, it looks really great.

**Comment by wrightaprilm** [comment]
I'm going to re-open this issue. It occurs to me that in the setup, we haven't had them clone anything (so there isn't a Data Carpentry repository on their computer containing the script), nothing in our setup asks them to do anything at the cmd line, and most of the learners won't have executed a python script before. So I'm thinking of moving this into the instructor guide and having the instructors make the call about how they tell learners to execute this script. But I wanted input from you, @hugobowne and @qjcg, before making the call on that.

**Comment by qjcg** [comment]
@wrightaprilm I agree that asking new learners with no programming experience to run a Python script could lead to confusion, and the fact that they won't have this script on their system is clearly an issue. So +1 for moving this into the instructor guide and making use of it on a per-group basis.

**Comment by hugobowne** [comment]
@wrightaprilm agreed completely.

**Pull request merged**
