### PR TITLE
Create 06b_matplotlib_plotting.ipynb

### PR DESCRIPTION
**Pull request by jfkoehler**
plots from lesson six carried out in matplotlib rather than ggplot

### CODE REVIEW

**Comment by wrightaprilm** [comment]
Hi Jacob, 

I wanted to have a look at the notebook before merging, and iPython notebooks are still weird for diffing. I think I'm looking at the right one [here](https://github.com/jfkoehler/python-ecology-lesson/blob/patch-1/_episodes/06-visualization-ggplot-python.ipynb). But I'm not seeing how it's different than our present notebook [here.](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_episodes/06-visualization-ggplot-python.ipynb). Am I looking in the right place? 

Thanks!

**Comment by jfkoehler** [comment]
Alison,

Yes, sorry about that.  I couldn't really figure out how to upload the
notebook, tried copy and pasting the raw notebook code but it seems that
didn't work.

I have a copy of the notebook on my github page and you can download it
from nbviewer here

http://nbviewer.jupyter.org/github/jfkoehler/jfkoehler.github.io/blob/master/carpentry_checkout/07b-Pandas-and-Matplotlib.ipynb

Let me know if you have any other questions.

Thanks!

Best,

Jacob

**Comment by wrightaprilm** [comment]
Looks great, thank you. It looks like this is for checkout? Let me know and I'll tag it as such.

**Comment by jfkoehler** [comment]
April,

Yes, it is for my instructor checkout.  Thanks!

Best,

Jacob

**Pull request merged**
