### PR TITLE
Lesson 2 - Revise the copy and reference section

### LINKED ISSUE #160: 02 copy example
Adjust text to suggest that the first copy attempt won't work

We can also reassign values within subsets of our DataFrame. But before we do that, let’s _try to _ make a copy of our DataFrame so as not to modify our original imported data.

```
#try to copy the surveys dataframe so we don't modify the original DataFrame
surveys_copy = surveys_df
```

```
#set the first three rows of data in the DataFrame to 0
surveys_copy[0:3] = 0
```

_At the end of the next section, repeat example code that shows a successful copy_

```
#set the first three rows of data in the DataFrame to 0
surveys_copy[0:3] = 0
surveys_copy.head()
surveys_df.head()
```

### PR DESCRIPTION
**Pull request by willingc**
Closes #160 and #161 

This is still a WIP. Copy and references are one of the most confusing concepts for those new to them. I believe it is better to be direct and precise in explaining these two concepts than to have the students experiment to figure out the difference.

Feedback welcome on this draft.

### CODE REVIEW

**Comment by tmorrell** [comment]
I think this is a great set of revisions.  The copy vs reference section is much clearer.

**Comment by willingc** [comment]
I've editing the entire lesson and am removing the WIP designation. Please review. Thanks!

**Comment by tracykteal** [comment]
Agree, the language and formatting adds a lot of clarity.

**Comment by wrightaprilm** [comment]
OK, I think we're good to go. I'm working through #147 right now, so I'm going to merge these ahead so I can read these changes as I do that.

Thanks so much!

**Comment by willingc** [comment]
Thanks @wrightaprilm @tracykteal @tmorrell for the review and merge.

**Pull request merged**
