### PR TITLE
Changing the mean weight to the sum of all weights

### PR DESCRIPTION
**Pull request by mboisson**
The mean weight across various species is rather meaningless. By changing it to the sum of the weights, we can relate this to the biomass of the plot 
https://en.wikipedia.org/wiki/Biomass_(ecology)

This makes the exercise more meaningful.

### CODE REVIEW

**Comment by wrightaprilm** [comment]
Sorry for being so late getting back to this. I'm a little hesitant to make changes that diverge the R and the python lessons unnecessarily. How would team R (@fmichonneau @aurielfournier ) feel about this change?

**Comment by fmichonneau** [comment]
I think the only time in the lesson we do something like this is in questions 4 of this challenge: http://www.datacarpentry.org/R-ecology-lesson/03-dplyr.html#challenge19

I'm open to making it more biologically relevant, but it would require refactoring the entire challenge...

**Comment by aurielfournier** [comment]
I agree with @fmichonneau

**Comment by wrightaprilm** [comment]
I could have sworn the R lesson did averages across species across plots in the Starting With Data lesson, but it looks like you aggregate the number of males and females caught across plots. Is that right (I know our templates are organized a little differently)? If so, I might create an issue for us to move to that example so the tasks between the two sets of lessons are broadly similar.

**Pull request closed without merging**
