### PR TITLE
Code formatting

### PR DESCRIPTION
**Pull request by tmorrell**
Update code blocks per issue #266.  Will not change the formatting until the template is updated.

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Thomas, I screwed up a bit: I did not check open pull requests before implementing these changes myself. Could you please rebase this PR on top of the latest gh-pages branch to see if I missed something? My apologies. :(

**Comment by trallard** [comment]
hey, @maxim-belkin @tmorrell does this still need rebasing? I was just going over the lesson and the issues and it seems that we could now close issue #266

**Comment by maxim-belkin** [comment]
I rebased it for @tmorrell

**Comment by maxim-belkin** [comment]
Thanks, @tmorrell for the PR and @trallard for the reminder!

**Comment by wrightaprilm** [comment]
Thanks for handling this - my availability is going to continue to be spotty due to 👶. I'm going to email the lead instructors of upcoming DC-python-ecology workshops (there's one Monday-Tuesday, not sure if more) and let them know the rebase occurred, if they want to make sure to grab the changes from upstream so the lessons render right.

**Comment by maxim-belkin** [comment]
I rebased the PR, nothing more. So all they have to do is `git pull`

**Comment by maxim-belkin** [comment]
Congrats on the 👶 ! :)

**Comment by wrightaprilm** [comment]
Oh, just the PR. Sorry, little scattered - I know there's a lesson rebase with my name on it somewhere.

**Comment by maxim-belkin** [comment]
> little scattered

that's totally understandable :)

**Comment by trallard** [comment]
Congratulations on the 👶 , don't worry too much about this @maxim-belkin is doing awesome with the maintenance and I am tagging along 😛

**Pull request merged**
