### PR TITLE
guide.md: removing deprecated challenge

### PR DESCRIPTION
**Pull request by NPalopoli**
Removed mention and response to challenge that was removed from lesson 06-loops-and-functions.md

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Thanks for the pull request, @NPalopoli. Let's, however, instead of simply deleting it add it to a new file called `extra_exercises.md`: create a new file in `_extras` directory, add the following header to it:
```
---                                                                                                     
layout: page                                                                                            
title: "Additional Exercises"                                                                           
permalink: /extra_exercises/                                                                            
---                                                                                                     
A collection of exercises that have been either removed from                                            
or not (yet) added to the main lesson.   
```
and then move that exercise there.

**Comment by wrightaprilm** [comment]
Good call, @maxim-belkin. As these lessons get fuller and fuller, it will be good to have infrastructure to store exercises that are perfectly nice, and an instructor might want to use as they customize the material, but don't currently fit in the main flow of the lesson.

**Comment by NPalopoli** [comment]
Good idea @maxim-belkin. I've created this file in PR #347 although I opted for `extra_challenges.md` as the file name. Please go ahead and accept the commit to remove the exercise here.

**Comment by maxim-belkin** [comment]
'extra_challenges' is fine. Thanks, @NPalopoli! 

@wrightaprilm, Let's merge this one when @NPalopoli  updates that other one with the proper format for challenges.

**Comment by wrightaprilm** [comment]
Thanks all!

**Pull request merged**
