### PR TITLE
Update intro-to-python episode

### PR DESCRIPTION
**Pull request by katrintirok**
Rewritten introduction episode to better suit novices. Split from #257

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Hi, @katrintirok. I'm a backup maintainer.

Could you please rebase this PR on top of the latest gh-pages branch? I can help you with that if you're using git on the command line.

**Comment by katrintirok** [comment]
I just checked this episode once more and made sure that there is no reference to spyder that may be confusing. How can the episode be further enhanced? 
It introduces some important concepts suitable to novices that are not covered in the current introduction. It also leaves out more advanced concepts that are not necessary for the following episodes or are introduced later.

**Comment by maxim-belkin** [comment]
I  rebased this PR.
Personally, I think the change is too drastic...

**Comment by maxim-belkin** [comment]
It seems that the episode is overloaded.

**Comment by tobyhodges** [comment]
I'm helping the current lesson Maintainers process outstanding pull requests on this repository, in preparation for [transition to the new lesson infrastructure](https://carpentries.github.io/workbench/faq.html#update-fork-from-styles).

Although this PR was opened a long time ago, the suggested changes may still be relevant. However, the scale of the change being proposed is quite large, and I believe it should be discussed by the Curriculum Advisors. Indeed this PR is mentioned in #259, which was tagged for referral to the CAC. 

Unfortunately, I doubt that we have time for that discussion to happen and the changes here to be resolved before the Workbench transition takes place, so I am going to close this and comment on #259 to encourage the CAC to discuss it. If the CAC recommend changes similar to those proposed here by @katrintirok, we can point community members to this PR as inspiration for the needed updates. 

Thank you for contributing @katrintirok, I'm sorry to have to close this without a satisfactory resolution.

**Pull request closed without merging**
