### PR TITLE
Instructor edits

### PR DESCRIPTION
**Pull request by tmorrell**
Updates to instructor guide to correct some mistakes found during issue creation process

### CODE REVIEW

**Comment by willingc** [comment]
Looks like this needs a rebase.

**Comment by tmorrell** [comment]
Should be good to merge now

**Comment by willingc** [comment]
@tmorrell Reviewed. Please merge as I do not have push privileges. Thanks too!

**Comment by wrightaprilm** [comment]
It looks like we're good now. Going to merge.

**Pull request merged**
