### PR TITLE
Update 05-merging-data.md, possible mistake in output directory  name

### PR DESCRIPTION
**Pull request by jarrodscott**
There is no `data_output` directory nor has this been created at this point (lines 126 & 136)  in the lesson. Suggest changing to `data` :)

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Thanks for pointing this out, @jarrodscott. 

```
git log --full-history -p -- data_output
```
reveals that `data_output` directory was removed from this repo in 6f05f1c9d51afc44a8151fa824a4eb9ff9a2bdc7. Now, It is mentioned in the first episode:

>  and we will later create a `data_output/` folder when we learn how to export data

What do you think is the best course of action here: update wording in the first episode or add instructions on how to create `data_output` directory (and, if so should we create a directory in a shell, Jupyter notebook, or using `os.mkdir`)?

**Comment by jarrodscott** [comment]
@maxim-belkin of course! It is mentioned on L112 of lesson 00. I am afraid this is my bad. The instructions in the first episode clearly state that we will need to create additional directories (inc. `data_output/`). Sorry for clogging your bandwidth :)

I think in lesson 5 adding perhaps an instruction like *"If you have not already done so, create a new directory called `data_output/`*. Then leave it up to the student on how they wish to create a new directory since there seems to be several options (I am a python newbie, but that is my impression).

**Comment by maxim-belkin** [comment]
I'd like the lesson to provide all the necessary instructions and/or data (folders).
Saving output to the `data` folder seems fine for the intents and purposes of the lesson, so let's remove the note about the `data_output` folder and make sure it's not used or mentioned anywhere else.

**Comment by maxim-belkin** [comment]
a gentle ping, @jarrodscott :)

**Comment by maxim-belkin** [comment]
Many thanks for your contribution, @jarrodscott!

**Pull request merged**
