### PR TITLE
Plotnine conversion of the plotting episode

### PR DESCRIPTION
**Pull request by stijnvanhoey**
As currently discussed in #246, the `ggpy` package currently used in the plotting episode provides a Grammar of Graphics implementation, but seems still unstable and no longer actively maintained. As the syntax of `plotnine` is very similar and the package actively maintained, the conversion seems valid.

Even though I do understand the conversion is maybe a decision that need to be made broader, the main reason I'm putting this PR already out is the structure and rendering of the current episode. A challenge is currently a title (actually twice), a solution spread over 5 code blocks without any textual clarification,...

Furthermore, I did my best to adapt the flow of the episode to counteract the current 'advanced' feeling as reported by #226 @colinmorris maybe you could review this with respect to your issue?

### CODE REVIEW

**Comment by has2k1** [comment]
For an alias of `plotnine`, you should consider `p9` instead of `pn`. I have seen `plotnine` abbreviated that way in a couple of places.

**Comment by stijnvanhoey** [comment]
Thanks for the suggestion, I'll convert the aliases!

**Comment by wrightaprilm** [comment]
I'm not going to get a chance to look in any depth at this  pull request until next week. I'm going to see if I can solicit some extra hands-on to take a peek both at this and the wider discussion surrounding plotting, as well. One feasible thing might be to put the lesson using p9 on a separate branch that instructors could check out from.

**Comment by trallard** [comment]
@wrightaprilm do you need help with this? I can have a look at this PR over the BBQ bonanza

**Comment by wrightaprilm** [comment]
@trallard Absolutely, more eyes on this, the better!

**Comment by wrightaprilm** [comment]
All right, this passes checks on my Mac and PC. I'm going to merge, then file a new issue asking for folks to check it. Thanks so much for your work on this lesson!

**Comment by colinmorris** [comment]
Sorry, I'm late to the party on this PR, but I just wanted to say that, in terms of the pandas complexity I brought up in #226, I think this is a huge improvement!

Just to demystify it even further, my one suggestion would be to show excerpts of the dataframes/series you're getting back when you do the `yearly_counts` stuff. I filed an overall issue about showing outputs here: #268.

**Pull request merged**
